### PR TITLE
Gold bomb flee code

### PR DESCRIPTION
**Pull request by MatusGuy**

### CODE REVIEW

**Comment by MatusGuy** [comment]
:skull:

**Comment by Rusty-Box** [comment]
Gold Bomb still stops when reaching a ledge even though there is safe ground to stand.

**Comment by Rusty-Box** [comment]
Gold Bomb also falls from ledges when walking normally, instead of just when fleeing.
There is still easing when going from flee -> walk
A little longer realization timer for Gold Bomb when runnig away far enough from the target

**Comment by Rusty-Box** [comment]
Gold Bomb currently doesn't turn around if the target is in front of them while running away.
E.g. Gold Bomb sees Tux, runs away, Tux catches up and jumps right in front of Gold Bomb, they should jump again in shock and run the other way

**Comment by MatusGuy** [comment]
Should the bomb be able to detect tux from a wall?

**Pull request merged**
